### ISSUE TITLE
[Feature Request] Streaming a window from PC to 3DS

### ISSUE THREAD

**Issue by thejsa** [MarcuzD/3DSCPlus#1]
It would be pretty neat if this app could stream a window on the PC to the 3DS?
eg. streaming a Dolphin window to the 3DS (even better if the app has an option for side-by-side 3D display ;) )

I would take this on myself but my C skills aren't very good, hehe.

**Comment by MarcuzD** [comment]
Welp, I *also* wanted streaming, but it would increase the input latency quite a bit, and the amount of bytes I can send in one frame is very tiny for things like this. Sorry :/

**Comment by thejsa** [comment]
Ah, no problem. :3
